### ISSUE TITLE
Post Christmas Task list

### ISSUE THREAD

**Issue by sampov2** [fmidev/stac-browser#10]
* [ ] Use correct axis labels (currently they are hard coded). See MapComponents.tsx where the `bands` array is created: the contents of that array should be stored in the local state of MapComponent and passed on to the GraphedView. You can either modify `graphData` to be an object that contains both bands and the data arrays, or use separate attributes for the GraphedView component.
* [ ] Make sure the colors of the timeseries in the graph match the R / G / B setting for each band. The current `bands` array only contains which bands in what order are in the graph data, but not information as to what color needs to be used for each band. To do this in GraphedView, you can either modify the way you pass the bands information to the GraphedView (done above), or pass the `mapObject.channelSettings` object to GraphedView.
* [ ] Show inspectionDate and comparisonDate on the time series. Make sure the annotations are visible regardless if there is graph data for that date.
* [ ] If the comparisonDate is outside the time range chosen for the graph (2, 4, 6 months), then extend the time range to also show the comparison date. Note that the comparisonDate can be either before of after inspectionDate
* [ ] Have the graph set the comparisonDate in the state when the user clicks on the graph
* [ ] Make visually clear that timeseries graphs belong to a particular map (for example by drawing a slight border that extends up to the mapcomponent)
* [ ] Make sure they layout of the application works well in situations where there are so many maps that they span to multiple rows and some but not all have time series graphs visible. 
* [ ] Popup labels in the timeseries graph should name each axis
